### ISSUE TITLE
Using @mentions

### ISSUE THREAD

**Issue by lancecarlson** [frostly/rust-slack#19]
In the docs of slack it says you should be able to do <@U123> to mention a particular user in your workspace. I tried this and it didn't work using Text. I'm assuming because Text escapes characters. I also looked at Link, but that accepts two arguments, not one. Is this supposed to work differently somehow?

https://api.slack.com/docs/message-formatting#linking_to_channels_and_users

**Comment by compressed** [comment]
Good point. For now, you can use set [link_names](https://docs.rs/slack-hook/0.6.0/slack_hook/struct.PayloadBuilder.html#method.link_names) to true.

I was also reading https://api.slack.com/changelog/2017-09-the-one-about-usernames, which indicates `link_names` is going to be deprecated. I think the best course of action would be to make change `text` to be an `Option` for `SlackLink`. Open to a PR around that if you're interested.

**Comment by compressed** [comment]
Fixed in #21
