### ISSUE TITLE
Update curl to >= 0.2.17

### ISSUE THREAD

**Issue by JoshBlake** [frostly/rust-slack#4]
On Rustc nightly (tested 2016-03-17) the rust crate will fail with a segmentation fault due to a failure in curl crate. This can be fixed by updating the curl to >=0.2.17:

```cargo update -p curl```

**Comment by Icelle** [comment]
I just tested this using `rustc 1.9.0-nightly (b678600ac 2016-03-29)` and it builds successfully; it's pulling in curl `0.2.18` now. Maybe you just needed to run the `cargo update` command locally on your project so rust-slack could get the updated dependencies? I don't think there is any change required in this crate.

Let me know if you are still experiencing any issues.

Thanks!

**Comment by JoshBlake** [comment]
Yes, as I indicated doing cargo update does fix it. I wanted to make sure it is noted somewhere so that other users can find the fix easier, if anyone else updated Rust and wondered why their project seg faults. It's harder to find than a compiler error.

Since older Curl versions are broken and Rust nightly will eventually mature, ideally this crate dependencies should be updated to require Curl >= 0.2.17.

**Comment by compressed** [comment]
Closed in #6
